### ISSUE TITLE
node.yml problem

### ISSUE THREAD

**Issue by jjhesk** [WilsonBillkia/bane#4]
what is the proper setup for node.yaml ?
I open the file with empty config
```
# bane config v0.8
#
---
- hosts: all
  roles:
    - node
...

```

- Deploy your public key to your nodes
- Install requirements to all nodes (build-essential, libssl-dev, unzip)
- Install screen, htop, tcpdump, tree to all nodes (management tools for headless maintenance and monitoring)

How to acquire the public key to the node?
does it have an example? @WilsonBillkia

**Comment by WilsonBillkia** [comment]
hi, regarding node.yaml that is the full config, the tasks you seek are in roles/node/tasks/main.yml file 

re key management - its tricky to advise there, ill check the docs again but I intentionally left that blank more or less because its a very deep topic. But as long as your public key is on the box in the default location for the linux distro - it should just work.

**Comment by WilsonBillkia** [comment]
think this is closed now.
